# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MedicalApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MedicalApp

  target 'MedicalAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MedicalAppUITests' do
    # Pods for testing
  end

pod 'ReadMoreTextView'

end
